sylius_resource:
    resources:
        app.catalog_item:
            driver: doctrine/orm
            classes:
                model: App\Entity\CatalogItem
                form:  App\Form\Type\CatalogItemType
        app.catalog:
            driver: doctrine/orm
            classes:
                model: App\Entity\Catalog
                form:  App\Form\Type\CatalogType
