sylius_resource:
  resources:
    app.alarm:
      driver: doctrine/orm
      classes:
        model: App\Entity\Alarm
        repository: App\Repository\AlarmRepository
        form: App\Form\Type\AlarmType
