app_admin_catalog_item:
  resource: |
    alias: app.catalog_item
    section: admin
    templates: "admin/crud"
    grid: app_admin_catalog_item
    redirect: update
    permission: true
    except: [show]
    vars:
      all:
        subheader: 'Продукты'
  type: sylius.resource
  prefix: /admin
