app_admin_catalog_item_create:
  path: /admin/catalog_items/new
  methods: [GET, POST]
  defaults:
    _controller: app.controller.catalog_item::createAction
    _sylius:
      section: admin
      template: admin/crud/create.html.twig
      permission: true

app_admin_catalog_item_update:
  path: /admin/catalog_items/{id}/edit
  methods: [GET, PUT, PATCH]
  requirements:
    id: \d+
  defaults:
    _controller: app.controller.catalog_item::updateAction
    _sylius:
      section: admin
      template: admin/crud/update.html.twig
      permission: true

app_admin_catalog_item_delete:
  path: /admin/catalog_items/{id}
  methods: [DELETE]
  requirements:
    id: \d+
  defaults:
    _controller: app.controller.catalog_item::deleteAction
    _sylius:
      section: admin
      permission: true

app_admin_catalog_item:
  resource: |
    alias: app.catalog_item
    section: admin
    templates: "admin/crud"
    grid: app_admin_catalog_item
    path: /admin/catalog_items
    permission: true
    except: [show]
  type: sylius.resource

