app_admin_catalog_create:
  path: /admin/catalogs/new
  methods: [GET, POST]
  defaults:
    _controller: app.controller.catalog::createAction
    _sylius:
      section: admin
      template: admin/crud/create.html.twig
      permission: true

app_admin_catalog_update:
  path: /admin/catalogs/{id}/edit
  methods: [GET, PUT, PATCH]
  requirements:
    id: \d+
  defaults:
    _controller: app.controller.catalog::updateAction
    _sylius:
      section: admin
      template: admin/crud/update.html.twig
      permission: true

app_admin_catalog_delete:
  path: /admin/catalogs/{id}
  methods: [DELETE]
  requirements:
    id: \d+
  defaults:
    _controller: app.controller.catalog::deleteAction
    _sylius:
      section: admin
      permission: true

app_admin_catalog_item:
  resource: |
    alias: app.catalog_item
    section: admin
    templates: "admin/crud"
    grid: app_admin_catalog
    path: /admin/catalogs
    permission: true
    except: [show]
  type: sylius.resource

