app_admin_catalog_group_create:
    path: /admin/catalog_groups/new
    methods: [GET, POST]
    defaults:
        _controller: app.controller.catalog_groups:createAction
        _sylius:
            section: admin
            template: admin/crud/create.html.twig
            permission: true

app_admin_catalog_group_update:
    path: /admin/catalog_groups/{id}/edit
    methods: [GET, PUT, PATCH]
    requirements:
        id: \d+
    defaults:
        _controller: app.controller.catalog_group:updateAction
        _sylius:
            section: admin
            template: admin/crud/update.html.twig
            permission: true

app_admin_catalog_groups_delete:
    path: /admin/catalog_groups/{id}
    methods: [DELETE]
    requirements:
        id: \d+
    defaults:
        _controller: app.controller.catalog_groups:deleteAction
        _sylius:
            section: admin
            permission: true

app_admin_catalog_group:
    resource: |
        alias: app.catalog_groups
        section: admin
        templates: "admin/crud"
        grid: app_admin_catalog_group
        path: /admin/catalog_groups
        permission: true
        except: [show]
    type: sylius.resource
